---
# handlers file for role_misp

- name: restart_php_fpm # noqa: name[casing]
  ansible.builtin.systemd:
    name: php-fpm
    state: restarted

- name: restart_httpd # noqa: name[casing]
  ansible.builtin.systemd:
    name: httpd
    state: restarted
